name: 'Crypto Keys for Actions'

description: 'Create random key and vector pair per deployment'

author: 'frytg'

inputs:
  output-path:
    required: true
    description: 'Filepath in the repository used for final JSON file'
  iv-length:
    required: false
    description: 'Desired iv length'
  key-length:
    required: false
    description: 'Desired key length'
  key:
    required: false
    description: 'Optional key used to overwrite random generation'

runs:
  using: 'node12'
  main: 'dist/index.js'

branding:
  icon: 'lock'
  color: 'yellow'